from .__about__ import __version__
from .api import (
    create_task_manager,
    start_task,
    start_task_in_process,
    start_task_in_thread,
)
from .func import (
    as_result,
    as_result_async,
    do,
    do_async,
    final,
    partial,
    sleep,
    sleep_blocking,
)
from .manager import TaskManager
from .results import (
    NOTHING,
    Err,
    IsNothingError,
    IsNotNothingError,
    IsNotOkError,
    IsOkError,
    Nothing,
    Ok,
    Option,
    OptionError,
    Result,
    ResultError,
    Some,
    UnwrapError,
)
from .task import Task, TaskStatus

__all__ = [
    "__version__",
    "as_result_async",
    "as_result",
    "create_task_manager",
    "do_async",
    "do",
    "final",
    "partial",
    "sleep_blocking",
    "sleep",
    "start_task",
    "start_task_in_process",
    "start_task_in_thread",
    "Err",
    "IsNothingError",
    "IsNotNothingError",
    "IsNotOkError",
    "IsOkError",
    "Nothing",
    "Ok",
    "Option",
    "OptionError",
    "Panic",
    "Result",
    "ResultError",
    "Some",
    "Task",
    "TaskManager",
    "TaskStatus",
    "UnwrapError",
    "NOTHING",
]
